### ISSUE TITLE
雷華加入任務

### ISSUE THREAD

**Issue by Eden-Sun** [Eden-Sun/E402#6]
以下依序完成
### 冠東:
- [x] 1.叫雷華先丟一個issue，讓我加他入開發者
- [x] 6.改另一段code
### 仕華:
- [x] 2.安裝github工具
- [x] 3.clone 專案
- [x] 4.試改一小段code並commit
- [x] 5. 上傳(push)
- [x] 7. 下載冠東更新後的code(pull)

``` c
int a=0;
printf("%d",a);
```

**Comment by Khsh** [comment]
小烏龜的用好了 但是之前安裝的 Git Shell & GitHub 不會用到喔?

**Comment by Eden-Sun** [comment]
不會
